### ISSUE TITLE
Change the Accordian Props Structure.

### ISSUE THREAD

**Issue by ShubhamJoshi-1994** [reusejs/react#109]
The current Implementation of Accordion takes props in the following way:
```
accordionList: [
    {
      labelBaseProps: {
        label: 'Accordion 1',
      },
      content: ExpandedText,
      contentProps: {
        text: text,
      },
      variant: 'dark',
    },
    {
      labelBaseProps: {
        label: 'Accordion 2',
      },
      content: ExpandedText,
      contentProps: {
        text: text,
      },
      variant: 'dark',
    },
    {
      labelBaseProps: {
        label: 'Accordion 3',
      },
      content: ExpandedText,
      contentProps: {
        text: text,
      },
      variant: 'dark',
      accordionSuffix: <LabelBase label='Suffix Text' />,
    },
  ],
```

Here Label props are of type string `label?: string;` but we need to pass components in it. For example an icon and a text. 
This is being allowed, but VS code gives an error.

To resolve this, In `LabelBaseProps` we'll need to make `label?: string;` => `label?: any;`

Or look for other solutions.

Also, the Above payload looks complex and I am unable to understand the purpose of content and content props intuitively. Maybe we should relook into that too.

**Comment by rjvim** [comment]
@ShubhamJoshi-1994

```
    <label
      htmlFor={props.htmlFor}
      className={finalClassNames}
      style={props.labelStyles}
    >
      {props.label}
    </label>
```

If `props.label` is going to be a component, not just a "string", is it actually a label or a button?

But, we can make `label?: any` not an issue.

**Comment by rjvim** [comment]
@ShubhamJoshi-1994 

label has been changed to ReactNode which can accept string or a component, and this is better way than just using `any`

![Screenshot 2022-09-15 at 9 53 58 AM](https://user-images.githubusercontent.com/23579455/190313986-295ca9ce-6716-4eda-88f2-362ec0b48fde.png)

May be you can use something like this if your problem is not solved?

Else can this issue be closed?
