### ISSUE TITLE
Not Able to override styles in Collapsible Accordian.

### ISSUE THREAD

**Issue by ShubhamJoshi-1994** [reusejs/react#110]
Collapsible Accordion uses BaseAccordian under it.

```
return (
    <div>
      {props.accordionList.map?.((item, index) => {
        return (
          <AccordionBase
            key={index}
            {...item}
            onClick={(val: boolean) => {
              if (val) {
                setExpandedIndex(index);
              }
            }}
            isExpanded={expandedIndex === index}
          />
        );
      })}
    </div>
  );
```

Props of Collapsible Accordion are:
```
 labelBaseProps?: LabelBaseProps;
 accordionList: AccordionBaseProps[];
 accordionSuffix?: any;
 variant?: string;
```

and Base Accordion has a prop called `accordionBaseClasses` which is not accessible from the Collapsible accordion. Meaning we can't override BaseAccordion styles if we are using Collapsible Accordion.

**What should happen?**
- We should allow collapsible Accordion to accept `accordionBaseClasses` and then pass them to the BaseAccordion either by destructuring or individually

**Comment by rjvim** [comment]
@ShubhamJoshi-1994 This seems similar to how to we did in multiple places. Once example can be found in: `packages/react/src/molecules/pickers/select/simple.tsx`

<img width="478" alt="Screenshot 2022-09-10 at 5 36 12 PM" src="https://user-images.githubusercontent.com/23579455/189482532-e20ee5de-711c-4a8b-9267-a961bebd6aeb.png">

---

In above case, the implementation is not correct to being with:

1. Interface should extend, not reimplement. Ex: packages/react/src/atoms/textInputs/password.tsx

Most probably that should solve the issue

**Comment by rjvim** [comment]
@ShubhamJoshi-1994 Can this be closed?
