### ISSUE TITLE
Required an update on PickerSelectSimple component in reuse-js.

### ISSUE THREAD

**Issue by arafatalim** [reusejs/react#191]
@ShreyDhyani 

#### Client's Requirement 
- On Property Search Dropdown, the Dropdown should close when clicked again.
- See the below image (Edited)
![Screenshot 2023-04-13 at 11 46 55 AM](https://user-images.githubusercontent.com/126658754/231670316-78087dcd-c565-4e5e-ac81-5672ec3bf3c2.png)

Previous one has changed to `Select Search Box` by @rajeshn95 
![Screenshot 2023-04-13 at 11 53 45 AM](https://user-images.githubusercontent.com/126658754/231671840-f50d6378-02a4-4e7f-b6ef-fda626e03456.png)

#### Blocker
 - In the current scenario, there is no option available to perform the above action. (Dropdown should close when clicked again).

#### Information 
- Sharing the `Reuse-JS` link of the required component - [PickerSelectSimple](https://react.reusejs.org/?path=/docs/molecules-pickers-select-single--default)
- Required Component is using in the following codebase -[AuctionBazaarApp/apps/blob/main/packages/app/components/SearchForm.tsx](https://github.com/AuctionBazaarApp/apps/blob/main/packages/app/components/SearchForm.tsx)

**Comment by ShreyDhyani** [comment]
Use prop `enableToggle` for **PickerSelectSimple**.

Pls check example here:https://react.reusejs.org/?path=/story/molecules-pickers-select-single--toggled-disable-search
